// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: archive.sql

package store

import (
	"context"
)

const deleteArchiveRecord = `-- name: DeleteArchiveRecord :exec
DELETE FROM archive_records WHERE id = ?1
`

func (q *Queries) DeleteArchiveRecord(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteArchiveRecord, id)
	return err
}

const deleteArchiveSection = `-- name: DeleteArchiveSection :exec
DELETE FROM archive_sections WHERE id = ?1
`

func (q *Queries) DeleteArchiveSection(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteArchiveSection, id)
	return err
}

const getArchiveRecord = `-- name: GetArchiveRecord :one
SELECT id, code, title, abstract, section, tags, archived_at, reading_minutes, body, refs, sort_order, updated_at FROM archive_records WHERE id = ?1
`

func (q *Queries) GetArchiveRecord(ctx context.Context, id string) (ArchiveRecord, error) {
	row := q.db.QueryRowContext(ctx, getArchiveRecord, id)
	var i ArchiveRecord
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Abstract,
		&i.Section,
		&i.Tags,
		&i.ArchivedAt,
		&i.ReadingMinutes,
		&i.Body,
		&i.Refs,
		&i.SortOrder,
		&i.UpdatedAt,
	)
	return i, err
}

const listArchiveRecords = `-- name: ListArchiveRecords :many
SELECT id, code, title, abstract, section, tags, archived_at, reading_minutes, body, refs, sort_order, updated_at FROM archive_records ORDER BY sort_order, archived_at DESC
`

func (q *Queries) ListArchiveRecords(ctx context.Context) ([]ArchiveRecord, error) {
	rows, err := q.db.QueryContext(ctx, listArchiveRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArchiveRecord
	for rows.Next() {
		var i ArchiveRecord
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Abstract,
			&i.Section,
			&i.Tags,
			&i.ArchivedAt,
			&i.ReadingMinutes,
			&i.Body,
			&i.Refs,
			&i.SortOrder,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchiveSections = `-- name: ListArchiveSections :many
SELECT id, code, label, sort_order FROM archive_sections ORDER BY sort_order, id
`

func (q *Queries) ListArchiveSections(ctx context.Context) ([]ArchiveSection, error) {
	rows, err := q.db.QueryContext(ctx, listArchiveSections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArchiveSection
	for rows.Next() {
		var i ArchiveSection
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Label,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertArchiveRecord = `-- name: UpsertArchiveRecord :one
INSERT INTO archive_records (
    id, code, title, abstract, section, tags, archived_at, reading_minutes,
    body, refs, sort_order
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8,
    ?9, ?10, ?11
)
ON CONFLICT(id) DO UPDATE SET
    code            = excluded.code,
    title           = excluded.title,
    abstract        = excluded.abstract,
    section         = excluded.section,
    tags            = excluded.tags,
    archived_at     = excluded.archived_at,
    reading_minutes = excluded.reading_minutes,
    body            = excluded.body,
    refs            = excluded.refs,
    sort_order      = excluded.sort_order,
    updated_at      = datetime('now')
RETURNING id, code, title, abstract, section, tags, archived_at, reading_minutes, body, refs, sort_order, updated_at
`

type UpsertArchiveRecordParams struct {
	ID             string `json:"id"`
	Code           string `json:"code"`
	Title          string `json:"title"`
	Abstract       string `json:"abstract"`
	Section        string `json:"section"`
	Tags           string `json:"tags"`
	ArchivedAt     string `json:"archived_at"`
	ReadingMinutes int64  `json:"reading_minutes"`
	Body           string `json:"body"`
	Refs           string `json:"refs"`
	SortOrder      int64  `json:"sort_order"`
}

func (q *Queries) UpsertArchiveRecord(ctx context.Context, arg UpsertArchiveRecordParams) (ArchiveRecord, error) {
	row := q.db.QueryRowContext(ctx, upsertArchiveRecord,
		arg.ID,
		arg.Code,
		arg.Title,
		arg.Abstract,
		arg.Section,
		arg.Tags,
		arg.ArchivedAt,
		arg.ReadingMinutes,
		arg.Body,
		arg.Refs,
		arg.SortOrder,
	)
	var i ArchiveRecord
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Abstract,
		&i.Section,
		&i.Tags,
		&i.ArchivedAt,
		&i.ReadingMinutes,
		&i.Body,
		&i.Refs,
		&i.SortOrder,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertArchiveSection = `-- name: UpsertArchiveSection :one
INSERT INTO archive_sections (id, code, label, sort_order)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT(id) DO UPDATE SET
    code       = excluded.code,
    label      = excluded.label,
    sort_order = excluded.sort_order
RETURNING id, code, label, sort_order
`

type UpsertArchiveSectionParams struct {
	ID        string `json:"id"`
	Code      string `json:"code"`
	Label     string `json:"label"`
	SortOrder int64  `json:"sort_order"`
}

func (q *Queries) UpsertArchiveSection(ctx context.Context, arg UpsertArchiveSectionParams) (ArchiveSection, error) {
	row := q.db.QueryRowContext(ctx, upsertArchiveSection,
		arg.ID,
		arg.Code,
		arg.Label,
		arg.SortOrder,
	)
	var i ArchiveSection
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Label,
		&i.SortOrder,
	)
	return i, err
}
