// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: experiences.sql

package store

import (
	"context"
)

const deleteExperience = `-- name: DeleteExperience :exec
DELETE FROM experiences WHERE id = ?1
`

func (q *Queries) DeleteExperience(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteExperience, id)
	return err
}

const getExperience = `-- name: GetExperience :one
SELECT id, period_start, period_end, company, role, location, summary, responsibilities, achievements, technologies, type, sort_order, updated_at FROM experiences WHERE id = ?1
`

func (q *Queries) GetExperience(ctx context.Context, id string) (Experience, error) {
	row := q.db.QueryRowContext(ctx, getExperience, id)
	var i Experience
	err := row.Scan(
		&i.ID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Company,
		&i.Role,
		&i.Location,
		&i.Summary,
		&i.Responsibilities,
		&i.Achievements,
		&i.Technologies,
		&i.Type,
		&i.SortOrder,
		&i.UpdatedAt,
	)
	return i, err
}

const listExperiences = `-- name: ListExperiences :many
SELECT id, period_start, period_end, company, role, location, summary, responsibilities, achievements, technologies, type, sort_order, updated_at FROM experiences ORDER BY sort_order, period_start DESC
`

func (q *Queries) ListExperiences(ctx context.Context) ([]Experience, error) {
	rows, err := q.db.QueryContext(ctx, listExperiences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Experience
	for rows.Next() {
		var i Experience
		if err := rows.Scan(
			&i.ID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Company,
			&i.Role,
			&i.Location,
			&i.Summary,
			&i.Responsibilities,
			&i.Achievements,
			&i.Technologies,
			&i.Type,
			&i.SortOrder,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExperience = `-- name: UpsertExperience :one
INSERT INTO experiences (
    id, period_start, period_end, company, role, location, summary,
    responsibilities, achievements, technologies, type, sort_order
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7,
    ?8, ?9, ?10, ?11, ?12
)
ON CONFLICT(id) DO UPDATE SET
    period_start     = excluded.period_start,
    period_end       = excluded.period_end,
    company          = excluded.company,
    role             = excluded.role,
    location         = excluded.location,
    summary          = excluded.summary,
    responsibilities = excluded.responsibilities,
    achievements     = excluded.achievements,
    technologies     = excluded.technologies,
    type             = excluded.type,
    sort_order       = excluded.sort_order,
    updated_at       = datetime('now')
RETURNING id, period_start, period_end, company, role, location, summary, responsibilities, achievements, technologies, type, sort_order, updated_at
`

type UpsertExperienceParams struct {
	ID               string `json:"id"`
	PeriodStart      string `json:"period_start"`
	PeriodEnd        string `json:"period_end"`
	Company          string `json:"company"`
	Role             string `json:"role"`
	Location         string `json:"location"`
	Summary          string `json:"summary"`
	Responsibilities string `json:"responsibilities"`
	Achievements     string `json:"achievements"`
	Technologies     string `json:"technologies"`
	Type             string `json:"type"`
	SortOrder        int64  `json:"sort_order"`
}

func (q *Queries) UpsertExperience(ctx context.Context, arg UpsertExperienceParams) (Experience, error) {
	row := q.db.QueryRowContext(ctx, upsertExperience,
		arg.ID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Company,
		arg.Role,
		arg.Location,
		arg.Summary,
		arg.Responsibilities,
		arg.Achievements,
		arg.Technologies,
		arg.Type,
		arg.SortOrder,
	)
	var i Experience
	err := row.Scan(
		&i.ID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Company,
		&i.Role,
		&i.Location,
		&i.Summary,
		&i.Responsibilities,
		&i.Achievements,
		&i.Technologies,
		&i.Type,
		&i.SortOrder,
		&i.UpdatedAt,
	)
	return i, err
}
