// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: frequencies.sql

package store

import (
	"context"
)

const deleteFrequency = `-- name: DeleteFrequency :exec
DELETE FROM frequencies WHERE id = ?1
`

func (q *Queries) DeleteFrequency(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFrequency, id)
	return err
}

const getFrequency = `-- name: GetFrequency :one
SELECT id, label, handle, url, icon, is_primary, sort_order FROM frequencies WHERE id = ?1
`

func (q *Queries) GetFrequency(ctx context.Context, id string) (Frequency, error) {
	row := q.db.QueryRowContext(ctx, getFrequency, id)
	var i Frequency
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Handle,
		&i.Url,
		&i.Icon,
		&i.IsPrimary,
		&i.SortOrder,
	)
	return i, err
}

const listFrequencies = `-- name: ListFrequencies :many
SELECT id, label, handle, url, icon, is_primary, sort_order FROM frequencies ORDER BY sort_order, id
`

func (q *Queries) ListFrequencies(ctx context.Context) ([]Frequency, error) {
	rows, err := q.db.QueryContext(ctx, listFrequencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Frequency
	for rows.Next() {
		var i Frequency
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Handle,
			&i.Url,
			&i.Icon,
			&i.IsPrimary,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFrequency = `-- name: UpsertFrequency :one
INSERT INTO frequencies (id, label, handle, url, icon, is_primary, sort_order)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
ON CONFLICT(id) DO UPDATE SET
    label      = excluded.label,
    handle     = excluded.handle,
    url        = excluded.url,
    icon       = excluded.icon,
    is_primary = excluded.is_primary,
    sort_order = excluded.sort_order
RETURNING id, label, handle, url, icon, is_primary, sort_order
`

type UpsertFrequencyParams struct {
	ID        string `json:"id"`
	Label     string `json:"label"`
	Handle    string `json:"handle"`
	Url       string `json:"url"`
	Icon      string `json:"icon"`
	IsPrimary int64  `json:"is_primary"`
	SortOrder int64  `json:"sort_order"`
}

func (q *Queries) UpsertFrequency(ctx context.Context, arg UpsertFrequencyParams) (Frequency, error) {
	row := q.db.QueryRowContext(ctx, upsertFrequency,
		arg.ID,
		arg.Label,
		arg.Handle,
		arg.Url,
		arg.Icon,
		arg.IsPrimary,
		arg.SortOrder,
	)
	var i Frequency
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Handle,
		&i.Url,
		&i.Icon,
		&i.IsPrimary,
		&i.SortOrder,
	)
	return i, err
}
