// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: missions.sql

package store

import (
	"context"
	"database/sql"
)

const deleteMission = `-- name: DeleteMission :exec
DELETE FROM missions WHERE id = ?1
`

func (q *Queries) DeleteMission(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMission, id)
	return err
}

const getMission = `-- name: GetMission :one
SELECT id, code, title, summary, description, status, role, duration_label, period_start, period_end, technologies, highlights, challenges, metrics, links, cover, gallery, featured, sort_order, updated_at FROM missions WHERE id = ?1
`

func (q *Queries) GetMission(ctx context.Context, id string) (Mission, error) {
	row := q.db.QueryRowContext(ctx, getMission, id)
	var i Mission
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Summary,
		&i.Description,
		&i.Status,
		&i.Role,
		&i.DurationLabel,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Technologies,
		&i.Highlights,
		&i.Challenges,
		&i.Metrics,
		&i.Links,
		&i.Cover,
		&i.Gallery,
		&i.Featured,
		&i.SortOrder,
		&i.UpdatedAt,
	)
	return i, err
}

const listMissions = `-- name: ListMissions :many
SELECT id, code, title, summary, description, status, role, duration_label, period_start, period_end, technologies, highlights, challenges, metrics, links, cover, gallery, featured, sort_order, updated_at FROM missions ORDER BY sort_order, code
`

func (q *Queries) ListMissions(ctx context.Context) ([]Mission, error) {
	rows, err := q.db.QueryContext(ctx, listMissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mission
	for rows.Next() {
		var i Mission
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Summary,
			&i.Description,
			&i.Status,
			&i.Role,
			&i.DurationLabel,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Technologies,
			&i.Highlights,
			&i.Challenges,
			&i.Metrics,
			&i.Links,
			&i.Cover,
			&i.Gallery,
			&i.Featured,
			&i.SortOrder,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMission = `-- name: UpsertMission :one
INSERT INTO missions (
    id, code, title, summary, description, status, role, duration_label,
    period_start, period_end, technologies, highlights, challenges, metrics,
    links, cover, gallery, featured, sort_order
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8,
    ?9, ?10, ?11, ?12, ?13, ?14,
    ?15, ?16, ?17, ?18, ?19
)
ON CONFLICT(id) DO UPDATE SET
    code           = excluded.code,
    title          = excluded.title,
    summary        = excluded.summary,
    description    = excluded.description,
    status         = excluded.status,
    role           = excluded.role,
    duration_label = excluded.duration_label,
    period_start   = excluded.period_start,
    period_end     = excluded.period_end,
    technologies   = excluded.technologies,
    highlights     = excluded.highlights,
    challenges     = excluded.challenges,
    metrics        = excluded.metrics,
    links          = excluded.links,
    cover          = excluded.cover,
    gallery        = excluded.gallery,
    featured       = excluded.featured,
    sort_order     = excluded.sort_order,
    updated_at     = datetime('now')
RETURNING id, code, title, summary, description, status, role, duration_label, period_start, period_end, technologies, highlights, challenges, metrics, links, cover, gallery, featured, sort_order, updated_at
`

type UpsertMissionParams struct {
	ID            string         `json:"id"`
	Code          string         `json:"code"`
	Title         string         `json:"title"`
	Summary       string         `json:"summary"`
	Description   string         `json:"description"`
	Status        string         `json:"status"`
	Role          string         `json:"role"`
	DurationLabel string         `json:"duration_label"`
	PeriodStart   string         `json:"period_start"`
	PeriodEnd     sql.NullString `json:"period_end"`
	Technologies  string         `json:"technologies"`
	Highlights    string         `json:"highlights"`
	Challenges    string         `json:"challenges"`
	Metrics       string         `json:"metrics"`
	Links         string         `json:"links"`
	Cover         string         `json:"cover"`
	Gallery       string         `json:"gallery"`
	Featured      int64          `json:"featured"`
	SortOrder     int64          `json:"sort_order"`
}

func (q *Queries) UpsertMission(ctx context.Context, arg UpsertMissionParams) (Mission, error) {
	row := q.db.QueryRowContext(ctx, upsertMission,
		arg.ID,
		arg.Code,
		arg.Title,
		arg.Summary,
		arg.Description,
		arg.Status,
		arg.Role,
		arg.DurationLabel,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Technologies,
		arg.Highlights,
		arg.Challenges,
		arg.Metrics,
		arg.Links,
		arg.Cover,
		arg.Gallery,
		arg.Featured,
		arg.SortOrder,
	)
	var i Mission
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Summary,
		&i.Description,
		&i.Status,
		&i.Role,
		&i.DurationLabel,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Technologies,
		&i.Highlights,
		&i.Challenges,
		&i.Metrics,
		&i.Links,
		&i.Cover,
		&i.Gallery,
		&i.Featured,
		&i.SortOrder,
		&i.UpdatedAt,
	)
	return i, err
}
