// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type ArchiveRecord struct {
	ID             string `json:"id"`
	Code           string `json:"code"`
	Title          string `json:"title"`
	Abstract       string `json:"abstract"`
	Section        string `json:"section"`
	Tags           string `json:"tags"`
	ArchivedAt     string `json:"archived_at"`
	ReadingMinutes int64  `json:"reading_minutes"`
	Body           string `json:"body"`
	Refs           string `json:"refs"`
	SortOrder      int64  `json:"sort_order"`
	UpdatedAt      string `json:"updated_at"`
}

type ArchiveSection struct {
	ID        string `json:"id"`
	Code      string `json:"code"`
	Label     string `json:"label"`
	SortOrder int64  `json:"sort_order"`
}

type Experience struct {
	ID               string `json:"id"`
	PeriodStart      string `json:"period_start"`
	PeriodEnd        string `json:"period_end"`
	Company          string `json:"company"`
	Role             string `json:"role"`
	Location         string `json:"location"`
	Summary          string `json:"summary"`
	Responsibilities string `json:"responsibilities"`
	Achievements     string `json:"achievements"`
	Technologies     string `json:"technologies"`
	Type             string `json:"type"`
	SortOrder        int64  `json:"sort_order"`
	UpdatedAt        string `json:"updated_at"`
}

type Frequency struct {
	ID        string `json:"id"`
	Label     string `json:"label"`
	Handle    string `json:"handle"`
	Url       string `json:"url"`
	Icon      string `json:"icon"`
	IsPrimary int64  `json:"is_primary"`
	SortOrder int64  `json:"sort_order"`
}

type Mission struct {
	ID            string         `json:"id"`
	Code          string         `json:"code"`
	Title         string         `json:"title"`
	Summary       string         `json:"summary"`
	Description   string         `json:"description"`
	Status        string         `json:"status"`
	Role          string         `json:"role"`
	DurationLabel string         `json:"duration_label"`
	PeriodStart   string         `json:"period_start"`
	PeriodEnd     sql.NullString `json:"period_end"`
	Technologies  string         `json:"technologies"`
	Highlights    string         `json:"highlights"`
	Challenges    string         `json:"challenges"`
	Metrics       string         `json:"metrics"`
	Links         string         `json:"links"`
	Cover         string         `json:"cover"`
	Gallery       string         `json:"gallery"`
	Featured      int64          `json:"featured"`
	SortOrder     int64          `json:"sort_order"`
	UpdatedAt     string         `json:"updated_at"`
}

type Pilot struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Callsign  string `json:"callsign"`
	Role      string `json:"role"`
	Available int64  `json:"available"`
	Location  string `json:"location"`
	Bio       string `json:"bio"`
	Manifesto string `json:"manifesto"`
	Stats     string `json:"stats"`
	Avatar    string `json:"avatar"`
	ResumeUrl string `json:"resume_url"`
	UpdatedAt string `json:"updated_at"`
}

type SiteCopy struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}

type Technology struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Category    string `json:"category"`
	Proficiency int64  `json:"proficiency"`
	Since       string `json:"since"`
	Description string `json:"description"`
	Planet      string `json:"planet"`
	Featured    int64  `json:"featured"`
	SortOrder   int64  `json:"sort_order"`
	UpdatedAt   string `json:"updated_at"`
}

type TrainingSim struct {
	Repo      string `json:"repo"`
	Code      string `json:"code"`
	Title     string `json:"title"`
	Summary   string `json:"summary"`
	Stack     string `json:"stack"`
	Year      int64  `json:"year"`
	RepoUrl   string `json:"repo_url"`
	SortOrder int64  `json:"sort_order"`
	UpdatedAt string `json:"updated_at"`
}
