// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pilot.sql

package store

import (
	"context"
)

const getPilot = `-- name: GetPilot :one
SELECT id, name, callsign, role, available, location, bio, manifesto, stats, avatar, resume_url, updated_at FROM pilot WHERE id = 1
`

func (q *Queries) GetPilot(ctx context.Context) (Pilot, error) {
	row := q.db.QueryRowContext(ctx, getPilot)
	var i Pilot
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Callsign,
		&i.Role,
		&i.Available,
		&i.Location,
		&i.Bio,
		&i.Manifesto,
		&i.Stats,
		&i.Avatar,
		&i.ResumeUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePilot = `-- name: UpdatePilot :one
UPDATE pilot SET
    name       = ?1,
    callsign   = ?2,
    role       = ?3,
    available  = ?4,
    location   = ?5,
    bio        = ?6,
    manifesto  = ?7,
    stats      = ?8,
    avatar     = ?9,
    resume_url = ?10,
    updated_at = datetime('now')
WHERE id = 1
RETURNING id, name, callsign, role, available, location, bio, manifesto, stats, avatar, resume_url, updated_at
`

type UpdatePilotParams struct {
	Name      string `json:"name"`
	Callsign  string `json:"callsign"`
	Role      string `json:"role"`
	Available int64  `json:"available"`
	Location  string `json:"location"`
	Bio       string `json:"bio"`
	Manifesto string `json:"manifesto"`
	Stats     string `json:"stats"`
	Avatar    string `json:"avatar"`
	ResumeUrl string `json:"resume_url"`
}

func (q *Queries) UpdatePilot(ctx context.Context, arg UpdatePilotParams) (Pilot, error) {
	row := q.db.QueryRowContext(ctx, updatePilot,
		arg.Name,
		arg.Callsign,
		arg.Role,
		arg.Available,
		arg.Location,
		arg.Bio,
		arg.Manifesto,
		arg.Stats,
		arg.Avatar,
		arg.ResumeUrl,
	)
	var i Pilot
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Callsign,
		&i.Role,
		&i.Available,
		&i.Location,
		&i.Bio,
		&i.Manifesto,
		&i.Stats,
		&i.Avatar,
		&i.ResumeUrl,
		&i.UpdatedAt,
	)
	return i, err
}
