// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	DeleteArchiveRecord(ctx context.Context, id string) error
	DeleteArchiveSection(ctx context.Context, id string) error
	DeleteExperience(ctx context.Context, id string) error
	DeleteFrequency(ctx context.Context, id string) error
	DeleteMission(ctx context.Context, id string) error
	DeleteSiteCopy(ctx context.Context, key string) error
	DeleteTechnology(ctx context.Context, id string) error
	DeleteTrainingSim(ctx context.Context, repo string) error
	GetArchiveRecord(ctx context.Context, id string) (ArchiveRecord, error)
	GetExperience(ctx context.Context, id string) (Experience, error)
	GetFrequency(ctx context.Context, id string) (Frequency, error)
	GetMission(ctx context.Context, id string) (Mission, error)
	GetPilot(ctx context.Context) (Pilot, error)
	GetSiteCopy(ctx context.Context, key string) (SiteCopy, error)
	GetTechnology(ctx context.Context, id string) (Technology, error)
	GetTrainingSim(ctx context.Context, repo string) (TrainingSim, error)
	ListArchiveRecords(ctx context.Context) ([]ArchiveRecord, error)
	ListArchiveSections(ctx context.Context) ([]ArchiveSection, error)
	ListExperiences(ctx context.Context) ([]Experience, error)
	ListFrequencies(ctx context.Context) ([]Frequency, error)
	ListMissions(ctx context.Context) ([]Mission, error)
	ListSiteCopy(ctx context.Context) ([]SiteCopy, error)
	ListTechnologies(ctx context.Context) ([]Technology, error)
	ListTrainingSims(ctx context.Context) ([]TrainingSim, error)
	UpdatePilot(ctx context.Context, arg UpdatePilotParams) (Pilot, error)
	UpsertArchiveRecord(ctx context.Context, arg UpsertArchiveRecordParams) (ArchiveRecord, error)
	UpsertArchiveSection(ctx context.Context, arg UpsertArchiveSectionParams) (ArchiveSection, error)
	UpsertExperience(ctx context.Context, arg UpsertExperienceParams) (Experience, error)
	UpsertFrequency(ctx context.Context, arg UpsertFrequencyParams) (Frequency, error)
	UpsertMission(ctx context.Context, arg UpsertMissionParams) (Mission, error)
	UpsertSiteCopy(ctx context.Context, arg UpsertSiteCopyParams) (SiteCopy, error)
	UpsertTechnology(ctx context.Context, arg UpsertTechnologyParams) (Technology, error)
	UpsertTrainingSim(ctx context.Context, arg UpsertTrainingSimParams) (TrainingSim, error)
}

var _ Querier = (*Queries)(nil)
