// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: site_copy.sql

package store

import (
	"context"
)

const deleteSiteCopy = `-- name: DeleteSiteCopy :exec
DELETE FROM site_copy WHERE key = ?1
`

func (q *Queries) DeleteSiteCopy(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteSiteCopy, key)
	return err
}

const getSiteCopy = `-- name: GetSiteCopy :one
SELECT "key", value, updated_at FROM site_copy WHERE key = ?1
`

func (q *Queries) GetSiteCopy(ctx context.Context, key string) (SiteCopy, error) {
	row := q.db.QueryRowContext(ctx, getSiteCopy, key)
	var i SiteCopy
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const listSiteCopy = `-- name: ListSiteCopy :many
SELECT "key", value, updated_at FROM site_copy ORDER BY key
`

func (q *Queries) ListSiteCopy(ctx context.Context) ([]SiteCopy, error) {
	rows, err := q.db.QueryContext(ctx, listSiteCopy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SiteCopy
	for rows.Next() {
		var i SiteCopy
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSiteCopy = `-- name: UpsertSiteCopy :one
INSERT INTO site_copy (key, value)
VALUES (?1, ?2)
ON CONFLICT(key) DO UPDATE SET
    value      = excluded.value,
    updated_at = datetime('now')
RETURNING "key", value, updated_at
`

type UpsertSiteCopyParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertSiteCopy(ctx context.Context, arg UpsertSiteCopyParams) (SiteCopy, error) {
	row := q.db.QueryRowContext(ctx, upsertSiteCopy, arg.Key, arg.Value)
	var i SiteCopy
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}
