// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: technologies.sql

package store

import (
	"context"
)

const deleteTechnology = `-- name: DeleteTechnology :exec
DELETE FROM technologies WHERE id = ?1
`

func (q *Queries) DeleteTechnology(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTechnology, id)
	return err
}

const getTechnology = `-- name: GetTechnology :one
SELECT id, name, category, proficiency, since, description, planet, featured, sort_order, updated_at FROM technologies WHERE id = ?1
`

func (q *Queries) GetTechnology(ctx context.Context, id string) (Technology, error) {
	row := q.db.QueryRowContext(ctx, getTechnology, id)
	var i Technology
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Proficiency,
		&i.Since,
		&i.Description,
		&i.Planet,
		&i.Featured,
		&i.SortOrder,
		&i.UpdatedAt,
	)
	return i, err
}

const listTechnologies = `-- name: ListTechnologies :many
SELECT id, name, category, proficiency, since, description, planet, featured, sort_order, updated_at FROM technologies ORDER BY sort_order, name
`

func (q *Queries) ListTechnologies(ctx context.Context) ([]Technology, error) {
	rows, err := q.db.QueryContext(ctx, listTechnologies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Technology
	for rows.Next() {
		var i Technology
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Proficiency,
			&i.Since,
			&i.Description,
			&i.Planet,
			&i.Featured,
			&i.SortOrder,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTechnology = `-- name: UpsertTechnology :one
INSERT INTO technologies (id, name, category, proficiency, since, description, planet, featured, sort_order)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
ON CONFLICT(id) DO UPDATE SET
    name        = excluded.name,
    category    = excluded.category,
    proficiency = excluded.proficiency,
    since       = excluded.since,
    description = excluded.description,
    planet      = excluded.planet,
    featured    = excluded.featured,
    sort_order  = excluded.sort_order,
    updated_at  = datetime('now')
RETURNING id, name, category, proficiency, since, description, planet, featured, sort_order, updated_at
`

type UpsertTechnologyParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Category    string `json:"category"`
	Proficiency int64  `json:"proficiency"`
	Since       string `json:"since"`
	Description string `json:"description"`
	Planet      string `json:"planet"`
	Featured    int64  `json:"featured"`
	SortOrder   int64  `json:"sort_order"`
}

func (q *Queries) UpsertTechnology(ctx context.Context, arg UpsertTechnologyParams) (Technology, error) {
	row := q.db.QueryRowContext(ctx, upsertTechnology,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.Proficiency,
		arg.Since,
		arg.Description,
		arg.Planet,
		arg.Featured,
		arg.SortOrder,
	)
	var i Technology
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Proficiency,
		&i.Since,
		&i.Description,
		&i.Planet,
		&i.Featured,
		&i.SortOrder,
		&i.UpdatedAt,
	)
	return i, err
}
