// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: training_sims.sql

package store

import (
	"context"
)

const deleteTrainingSim = `-- name: DeleteTrainingSim :exec
DELETE FROM training_sims WHERE repo = ?1
`

func (q *Queries) DeleteTrainingSim(ctx context.Context, repo string) error {
	_, err := q.db.ExecContext(ctx, deleteTrainingSim, repo)
	return err
}

const getTrainingSim = `-- name: GetTrainingSim :one
SELECT repo, code, title, summary, stack, year, repo_url, sort_order, updated_at FROM training_sims WHERE repo = ?1
`

func (q *Queries) GetTrainingSim(ctx context.Context, repo string) (TrainingSim, error) {
	row := q.db.QueryRowContext(ctx, getTrainingSim, repo)
	var i TrainingSim
	err := row.Scan(
		&i.Repo,
		&i.Code,
		&i.Title,
		&i.Summary,
		&i.Stack,
		&i.Year,
		&i.RepoUrl,
		&i.SortOrder,
		&i.UpdatedAt,
	)
	return i, err
}

const listTrainingSims = `-- name: ListTrainingSims :many
SELECT repo, code, title, summary, stack, year, repo_url, sort_order, updated_at FROM training_sims ORDER BY sort_order, year DESC
`

func (q *Queries) ListTrainingSims(ctx context.Context) ([]TrainingSim, error) {
	rows, err := q.db.QueryContext(ctx, listTrainingSims)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrainingSim
	for rows.Next() {
		var i TrainingSim
		if err := rows.Scan(
			&i.Repo,
			&i.Code,
			&i.Title,
			&i.Summary,
			&i.Stack,
			&i.Year,
			&i.RepoUrl,
			&i.SortOrder,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTrainingSim = `-- name: UpsertTrainingSim :one
INSERT INTO training_sims (repo, code, title, summary, stack, year, repo_url, sort_order)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
ON CONFLICT(repo) DO UPDATE SET
    code       = excluded.code,
    title      = excluded.title,
    summary    = excluded.summary,
    stack      = excluded.stack,
    year       = excluded.year,
    repo_url   = excluded.repo_url,
    sort_order = excluded.sort_order,
    updated_at = datetime('now')
RETURNING repo, code, title, summary, stack, year, repo_url, sort_order, updated_at
`

type UpsertTrainingSimParams struct {
	Repo      string `json:"repo"`
	Code      string `json:"code"`
	Title     string `json:"title"`
	Summary   string `json:"summary"`
	Stack     string `json:"stack"`
	Year      int64  `json:"year"`
	RepoUrl   string `json:"repo_url"`
	SortOrder int64  `json:"sort_order"`
}

func (q *Queries) UpsertTrainingSim(ctx context.Context, arg UpsertTrainingSimParams) (TrainingSim, error) {
	row := q.db.QueryRowContext(ctx, upsertTrainingSim,
		arg.Repo,
		arg.Code,
		arg.Title,
		arg.Summary,
		arg.Stack,
		arg.Year,
		arg.RepoUrl,
		arg.SortOrder,
	)
	var i TrainingSim
	err := row.Scan(
		&i.Repo,
		&i.Code,
		&i.Title,
		&i.Summary,
		&i.Stack,
		&i.Year,
		&i.RepoUrl,
		&i.SortOrder,
		&i.UpdatedAt,
	)
	return i, err
}
